---
- hosts: localhost
  environment:
    AWS_REGION: "{{aws_region}}"
    HOME: /root
  handlers:
    - import_tasks: handlers/server.yaml
  tasks:
    - import_tasks: tasks/setup.server.yaml
      become: true
  